set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g history-limit 100000
set -g mouse on
set -g focus-events on
set -g set-clipboard on
set -g renumber-windows on
set -g escape-time 10

set -g base-index 1
setw -g pane-base-index 1

set -g status-keys vi
setw -g mode-keys vi

unbind '"'
unbind %
bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send -X cancel
